name: Salesforce CI Pipeline

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Get the code
        uses: actions/checkout@v3

      - name: Step 2 - Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Step 3 - Verify CLI installed
        run: sf --version

      - name: Step 4 - Run PMD Static Analysis
        run: |
           wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F7.0.0/pmd-dist-7.0.0-bin.zip
           unzip pmd-dist-7.0.0-bin.zip
           pmd-bin-7.0.0/bin/pmd check --dir force-app --rulesets category/apex/bestpractices.xml --format text --fail-on-violation --minimum-priority 2
        