name: Salesforce CI Pipeline

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Get the code
        uses: actions/checkout@v3

      - name: Step 2 - Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Step 3 - Verify CLI installed
        run: sf --version
        
      - name: Step 4 - Authenticate via JWT
        run: |
          echo "${{ secrets.JWT_PRIVATE_KEY }}" > server.key
          sf org login jwt \
            --client-id ${{ secrets.CONSUMER_KEY }} \
            --jwt-key-file server.key \
            --username ${{ secrets.SF_USERNAME }} \
            --instance-url ${{ secrets.SF_INSTANCE_URL }} \
            --alias targetorg